<h1>Introduction to Numpy</h1>

- Creating arrays
- Multi-dimensional arrays
- Randomly generated arrays
- Element-wise operations
    - Comparison Operations
    - Logical Operations
- Summarizing Operations

In [2]:
import numpy as np

In [3]:
np

<module 'numpy' from '/usr/local/python/3.12.1/lib/python3.12/site-packages/numpy/__init__.py'>

<h2>Creating Arrays</h2>

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [7]:
a = np.array([1, 2, 3, 5, 7, 12])
a

array([ 1,  2,  3,  5,  7, 12])

In [8]:
a[2] = 10

In [9]:
a

array([ 1,  2, 10,  5,  7, 12])

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [12]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

<h2>Multi-dimensional Arrays</h2>

In [13]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [14]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
n[0, 1] = 20

In [16]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [17]:
n[0]

array([ 1, 20,  3])

In [18]:
n[2] = [1, 1, 1]

In [19]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [20]:
n[:, 1]

array([20,  5,  1])

In [21]:
n[0,:]

array([ 1, 20,  3])

In [22]:
n[:, 2] = [0,1,2]

In [23]:
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

<h2>Randomly Generated Arrays</h2>

In [24]:
np.random.seed(2)
100 * np.random.rand(5,2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [25]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [50]:
np.random.seed(2)
z = np.random.randint(low=0, high=100, size=(5,2))
z.shape[1]

2

<h2>Element-wise Operations</h2> 

In [27]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [28]:
a + 1

array([1, 2, 3, 4, 5])

In [29]:
a * 2

array([0, 2, 4, 6, 8])

In [30]:
b = (10 + (a * 2) ** 2 / 100)
b

array([10.  , 10.04, 10.16, 10.36, 10.64])

In [31]:
a + b

array([10.  , 11.04, 12.16, 13.36, 14.64])

In [32]:
a * b

array([ 0.  , 10.04, 20.32, 31.08, 42.56])

<h2>Comparison Operatons</h2>

In [33]:
a >= b

array([False, False, False, False, False])

In [34]:
a >= 2

array([False, False,  True,  True,  True])

In [35]:
b

array([10.  , 10.04, 10.16, 10.36, 10.64])

In [36]:
a > b

array([False, False, False, False, False])

In [37]:
a[a > b]

array([], dtype=int64)

<h2>Summarizing Operations</h2>

In [38]:
a.min()

np.int64(0)

In [39]:
a.max()

np.int64(4)

In [40]:
a.sum()

np.int64(10)

In [41]:
a.mean()

np.float64(2.0)

In [42]:
a.std()

np.float64(1.4142135623730951)

In [43]:
a

array([0, 1, 2, 3, 4])