<h1>Linear Algrebra Refresher</h1>

In [1]:
import numpy as np

<h2>Vector Operations</h2>

In [2]:
u = np.array([2,4,5,6])

In [3]:
u

array([2, 4, 5, 6])

In [4]:
v = np.array([1,0,0,2])

In [5]:
v

array([1, 0, 0, 2])

In [6]:
u + v

array([3, 4, 5, 8])

<h2>Multiplication</h2>

In [7]:
u * v

array([ 2,  0,  0, 12])

<h3>Vector-Vector Multiplication (Dot Product)</h3>

In [8]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]

    result = 0.0
    
    for i in range(n):
        result = result + u[i] * v[i]

    return result

In [9]:
w = vector_vector_multiplication(u, v)
w

np.float64(14.0)

<h3>Matrix-Vector Multiplication</h3>

In [25]:
U = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1],
])

U.shape[1]

4

In [ ]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]

    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)

    return result
        

In [12]:
matrix_vector_multiplication(U,v)

array([14.,  5.,  5.])

In [13]:
U.dot(v)

array([14,  5,  5])

<h3>Matrix-Matrix Multiplcation</h3>

In [27]:
V = np.array([
    [1,1,2],
    [0.0,5,1],
    [0,2,1],
    [2,1,0],
])

V.shape[0]

4

In [15]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1]

    result = np.zeros((num_rows, num_cols))

    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U,vi)
        result[:, i] = Uvi

    return result

In [16]:
matrix_matrix_multiplication(U,V)

array([[14., 14., 14.],
       [ 5.,  5.,  5.],
       [ 5.,  5.,  5.]])

In [17]:
U.dot(V)

array([[14., 38., 13.],
       [ 5., 15.,  5.],
       [ 5., 13.,  9.]])

<h3>Identity Matrix</h3>

In [18]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [19]:
I = np.eye(3)

In [20]:
V.dot(I)

array([[1., 1., 2.],
       [0., 5., 1.],
       [0., 2., 1.],
       [2., 1., 0.]])

<h3>Matrix Inverse</h3>

In [21]:
Vs = V[[0,1,2]]
Vs

array([[1., 1., 2.],
       [0., 5., 1.],
       [0., 2., 1.]])

In [22]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        ,  1.        , -3.        ],
       [ 0.        ,  0.33333333, -0.33333333],
       [ 0.        , -0.66666667,  1.66666667]])

In [23]:
Vs_inv.dot(Vs)

array([[ 1.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       [ 0.0000000e+00,  1.0000000e+00,  0.0000000e+00],
       [ 0.0000000e+00, -4.4408921e-16,  1.0000000e+00]])